import { LuChartNoAxesColumn } from "react-icons/lu";
import { MdOutlineDashboard } from "react-icons/md";
import { RiFileListLine, RiMoneyDollarCircleLine, RiNotificationLine, RiSettingsLine, RiUserLine, RiUserStarLine, RiVerifiedBadgeLine } from "react-icons/ri";
import CustomCoinIcon from "./custom-icons/DollarWithRing";
import { ShieldCheck } from "lucide-react";
import { FiFileText } from "react-icons/fi";




export const navLinks = [
  { title: "Dashboard", path: "/dashboard", icon: MdOutlineDashboard },
  { title: "Users", path: "/dashboard/users", icon:RiUserLine  },
  { title: "KYC Verification", path: "/dashboard/kyc", icon: RiFileListLine },
  { title: "Schemes", path: "/dashboard/schemes", icon: CustomCoinIcon },
  { title: "Payments", path: "/dashboard/payments", icon: RiMoneyDollarCircleLine },
  { title: "Reports", path: "/dashboard/reports", icon: LuChartNoAxesColumn  },
  { title: "Notifications", path: "/dashboard/notifications", icon: RiNotificationLine },
  { title: "Settings", path: "/dashboard/settings", icon: RiSettingsLine  },
];


export const dashboardStatData = [
  {
    title:"total users" ,
    data:"1245",
    icon:RiUserLine,
    percentage: 5.2,
    isGraph:false,
  },
    {
    title:"pending Kyc Validation" ,
    data:"47",
    icon:ShieldCheck,
    percentage: -2,
    isGraph:false,
  },
    {
    title:"revenue (MTD)" ,
    data:"AED 123000",
    icon:RiMoneyDollarCircleLine,
    percentage: 15.3,
    isGraph:true,
  },
    {
    title:"active schemes" ,
    data:"4",
    icon:CustomCoinIcon,
    percentage: 4,
    isGraph:false,
  },
]



export const dashboardSchemeData = [
  {
    userName:"rajesh kumar",
    scheme:"gold1",
    amount:12500,
    dueDate:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh ",
    scheme:"gold 2",
    amount:25000,
    dueDate:"2025-12-15T00:00:00Z"
  },
  {
    userName:" kumar",
    scheme:"gold1",
    amount:1564,
    dueDate:"2025-12-15T00:00:00Z"
  },
  {
    userName:"priya kumar",
    scheme:"start-up scheme",
    amount:12500,
    dueDate:"2025-12-15T00:00:00Z"
  },
  {
    userName:"sonu sharma",
    scheme:"gold 2",
    amount:5456,
    dueDate:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh thivari",
    scheme:"gold1",
    amount:12500,
    dueDate:"2025-12-15T00:00:00Z"
  },
]
export const dashboardKycData = [
  {
    userName:"rajesh thivari",
    idType:"emirates id",
    
    date:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh thivari",
    idType:"emirates id",
    
    date:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh thivari",
    idType:"emirates id",
    
    date:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh thivari",
    idType:"emirates id",
    
    date:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh thivari",
    idType:"emirates id",
    
    date:"2025-12-15T00:00:00Z"
  },
  {
    userName:"rajesh thivari",
    idType:"emirates id",
    
    date:"2025-12-15T00:00:00Z"
  },
]

export const recentActivities = [
  {
    message: "New user registered : Rajesh Kumar",
    timestamp: "2025-10-23 09:15:32",
    type: "success",
    department: "user",
  },
  {
    message: "Payment received from Anjali Sharma",
    timestamp: "2025-10-23 10:02:15",
    type: "success",
    department: "payments",
  },
  {
    message: "KYC approved for Priya Singh",
    timestamp: "2025-10-23 10:45:08",
    type: "success",
    department: "kyc",
  },
  {
    message: "Payment overdue for Rahul Verma",
    timestamp: "2025-10-23 11:12:49",
    type: "danger",
    department: "payments",
  },
  {
    message: "New policy enrollment by Sneha Kapoor",
    timestamp: "2025-10-23 11:35:22",
    type: "info",
    department: "schemes",
  },
  {
    message: "KYC rejected for Manish Sharma",
    timestamp: "2025-10-23 12:05:47",
    type: "danger",
    department: "kyc",
  },
  {
    message: "Payment received from Ankit Mehta",
    timestamp: "2025-10-23 12:25:31",
    type: "success",
    department: "payments",
  },
  {
    message: "New user registered: Simran Kaur",
    timestamp: "2025-10-23 12:48:10",
    type: "success",
    department: "user",
  },
  {
    message: "Payment overdue for Deepak Rao",
    timestamp: "2025-10-23 13:02:55",
    type: "danger",
    department: "payments",
  },
  {
    message: "Policy renewal completed by Anjali Sharma",
    timestamp: "2025-10-23 13:20:14",
    type: "success",
    department: "schemes",
  },
];




export const userData= [
  {
    ID: "AGD001",
    userName: "Priya Sharma",
    email: "priya.sharma@gmail.com",
    phoneNo: "+91 9876543210",
    joinDate: "2024-12-15T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 45000,
    schemes: ["gold1", "silver2"]
  },
  {
    ID: "AGD002",
    userName: "Rohit Verma",
    email: "rohit.verma@gmail.com",
    phoneNo: "+91 9823456712",
    joinDate: "2025-01-05T00:00:00Z",
    isActive: false,
    kycStatus: "pending",
    investment: 25000,
    schemes: ["platinum3"]
  },
  {
    ID: "AGD003",
    userName: "Aisha Khan",
    email: "aisha.khan@gmail.com",
    phoneNo: "+91 9901122334",
    joinDate: "2025-02-11T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 60000,
    schemes: ["gold1", "diamond4"]
  },
  {
    ID: "AGD004",
    userName: "Manoj Patil",
    email: "manoj.patil@gmail.com",
    phoneNo: "+91 9632587410",
    joinDate: "2025-03-02T00:00:00Z",
    isActive: false,
    kycStatus: "rejected",
    investment: 18000,
    schemes: ["silver2"]
  },
  {
    ID: "AGD005",
    userName: "Sneha Nair",
    email: "sneha.nair@gmail.com",
    phoneNo: "+91 9856743210",
    joinDate: "2025-01-25T00:00:00Z",
    isActive: true,
    kycStatus: "pending",
    investment: 52000,
    schemes: ["gold1", "silver2", "platinum3"]
  },
  {
    ID: "AGD006",
    userName: "Arjun Mehta",
    email: "arjun.mehta@gmail.com",
    phoneNo: "+91 9812345678",
    joinDate: "2025-03-10T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 75000,
    schemes: ["diamond4"]
  },
  {
    ID: "AGD007",
    userName: "Neha Gupta",
    email: "neha.gupta@gmail.com",
    phoneNo: "+91 9845123098",
    joinDate: "2025-02-19T00:00:00Z",
    isActive: false,
    kycStatus: "pending",
    investment: 30000,
    schemes: ["silver2"]
  },
  {
    ID: "AGD008",
    userName: "Aman Singh",
    email: "aman.singh@gmail.com",
    phoneNo: "+91 9815672309",
    joinDate: "2024-11-10T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 88000,
    schemes: ["gold1", "diamond4"]
  },
  {
    ID: "AGD009",
    userName: "Kavita Joshi",
    email: "kavita.joshi@gmail.com",
    phoneNo: "+91 9823344556",
    joinDate: "2025-04-05T00:00:00Z",
    isActive: true,
    kycStatus: "rejected",
    investment: 22000,
    schemes: ["silver2"]
  },
  {
    ID: "AGD010",
    userName: "Vikram Rao",
    email: "vikram.rao@gmail.com",
    phoneNo: "+91 9798765432",
    joinDate: "2025-02-01T00:00:00Z",
    isActive: false,
    kycStatus: "verified",
    investment: 45000,
    schemes: ["platinum3"]
  },
  {
    ID: "AGD011",
    userName: "Meera Iyer",
    email: "meera.iyer@gmail.com",
    phoneNo: "+91 9123456789",
    joinDate: "2024-12-28T00:00:00Z",
    isActive: true,
    kycStatus: "pending",
    investment: 64000,
    schemes: ["gold1"]
  },
  {
    ID: "AGD012",
    userName: "Ramesh Kumar",
    email: "ramesh.kumar@gmail.com",
    phoneNo: "+91 9876501234",
    joinDate: "2025-05-02T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 37000,
    schemes: ["silver2", "platinum3"]
  },
  {
    ID: "AGD013",
    userName: "Nisha Das",
    email: "nisha.das@gmail.com",
    phoneNo: "+91 9798123456",
    joinDate: "2025-03-22T00:00:00Z",
    isActive: false,
    kycStatus: "rejected",
    investment: 29000,
    schemes: ["gold1"]
  },
  {
    ID: "AGD014",
    userName: "Rahul Sen",
    email: "rahul.sen@gmail.com",
    phoneNo: "+91 9812456780",
    joinDate: "2025-04-10T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 91000,
    schemes: ["diamond4", "gold1"]
  },
  {
    ID: "AGD015",
    userName: "Ananya Mukherjee",
    email: "ananya.mukherjee@gmail.com",
    phoneNo: "+91 9809988776",
    joinDate: "2025-01-14T00:00:00Z",
    isActive: false,
    kycStatus: "pending",
    investment: 41000,
    schemes: ["silver2"]
  },
  {
    ID: "AGD016",
    userName: "Karan Thakur",
    email: "karan.thakur@gmail.com",
    phoneNo: "+91 9876112233",
    joinDate: "2024-11-22T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 58000,
    schemes: ["gold1", "platinum3"]
  },
  {
    ID: "AGD017",
    userName: "Pooja Reddy",
    email: "pooja.reddy@gmail.com",
    phoneNo: "+91 9811223344",
    joinDate: "2025-03-15T00:00:00Z",
    isActive: false,
    kycStatus: "rejected",
    investment: 19000,
    schemes: ["silver2"]
  },
  {
    ID: "AGD018",
    userName: "Deepak Mishra",
    email: "deepak.mishra@gmail.com",
    phoneNo: "+91 9822114455",
    joinDate: "2025-04-25T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 73000,
    schemes: ["gold1", "diamond4"]
  },
  {
    ID: "AGD019",
    userName: "Tina Paul",
    email: "tina.paul@gmail.com",
    phoneNo: "+91 9799776655",
    joinDate: "2024-12-05T00:00:00Z",
    isActive: false,
    kycStatus: "pending",
    investment: 32000,
    schemes: ["platinum3"]
  },
  {
    ID: "AGD020",
    userName: "Harish Nair",
    email: "harish.nair@gmail.com",
    phoneNo: "+91 9844332211",
    joinDate: "2025-05-10T00:00:00Z",
    isActive: true,
    kycStatus: "verified",
    investment: 81000,
    schemes: ["gold1", "silver2"]
  }
];

export const kycData = [
  {
    "ID": "KYC001",
    "userName": "Harish Nair",
    "aadhaarNumber": "9844 3322 1110",
    "level": 2,
    "date": "2025-05-10T00:00:00Z",
    "status": "verified",
    "priority": "high",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC002",
    "userName": "Sneha Kapoor",
    "aadhaarNumber": "1234 5678 9012",
    "level": 1,
    "date": "2025-03-22T00:00:00Z",
    "status": "under review",
    "priority": "medium",
    "reviewed": ""
  },
  {
    "ID": "KYC003",
    "userName": "Rohit Sharma",
    "aadhaarNumber": "5566 7788 9900",
    "level": 3,
    "date": "2024-11-15T00:00:00Z",
    "status": "verified",
    "priority": "high",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC004",
    "userName": "Anita Desai",
    "aadhaarNumber": "4321 8765 2109",
    "level": 1,
    "date": "2025-01-08T00:00:00Z",
    "status": "rejected",
    "priority": "high",
    "reviewed": ""
  },
  {
    "ID": "KYC005",
    "userName": "Vikram Patel",
    "aadhaarNumber": "7070 5050 3030",
    "level": 2,
    "date": "2025-06-30T00:00:00Z",
    "status": "under review",
    "priority": "medium",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC006",
    "userName": "Meera Iyer",
    "aadhaarNumber": "9988 7766 5544",
    "level": 3,
    "date": "2024-12-01T00:00:00Z",
    "status": "verified",
    "priority": "low",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC007",
    "userName": "Ajay Kumar",
    "aadhaarNumber": "1111 2222 3333",
    "level": 2,
    "date": "2025-07-19T00:00:00Z",
    "status": "pending",
    "priority": "low",
    "reviewed": ""
  },
  {
    "ID": "KYC008",
    "userName": "Pooja Reddy",
    "aadhaarNumber": "2468 1357 0246",
    "level": 1,
    "date": "2025-02-14T00:00:00Z",
    "status": "rejected",
    "priority": "medium",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC009",
    "userName": "Suresh Menon",
    "aadhaarNumber": "3141 5926 5358",
    "level": 3,
    "date": "2024-08-05T00:00:00Z",
    "status": "under review",
    "priority": "low",
    "reviewed": ""
  },
  {
    "ID": "KYC010",
    "userName": "Kavita Singh",
    "aadhaarNumber": "8686 8686 8686",
    "level": 2,
    "date": "2025-09-02T00:00:00Z",
    "status": "pending",
    "priority": "high",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC011",
    "userName": "Deepak Joshi",
    "aadhaarNumber": "0192 8374 6501",
    "level": 1,
    "date": "2024-10-21T00:00:00Z",
    "status": "under review",
    "priority": "medium",
    "reviewed": ""
  },
  {
    "ID": "KYC012",
    "userName": "Nisha Verma",
    "aadhaarNumber": "4455 6677 8899",
    "level": 3,
    "date": "2025-04-11T00:00:00Z",
    "status": "rejected",
    "priority": "high",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC013",
    "userName": "Manoj Tiwari",
    "aadhaarNumber": "1212 3434 5656",
    "level": 2,
    "date": "2025-08-16T00:00:00Z",
    "status": "verified",
    "priority": "high",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC014",
    "userName": "Rhea Paul",
    "aadhaarNumber": "9090 8080 7070",
    "level": 1,
    "date": "2024-09-09T00:00:00Z",
    "status": "pending",
    "priority": "medium",
    "reviewed": ""
  },
  {
    "ID": "KYC015",
    "userName": "Tarun Bhat",
    "aadhaarNumber": "5555 4444 3333",
    "level": 3,
    "date": "2025-06-05T00:00:00Z",
    "status": "verified",
    "priority": "low",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC016",
    "userName": "Geeta Rao",
    "aadhaarNumber": "2020 2020 2020",
    "level": 2,
    "date": "2025-01-27T00:00:00Z",
    "status": "rejected",
    "priority": "high",
    "reviewed": ""
  },
  {
    "ID": "KYC017",
    "userName": "Naveen Goyal",
    "aadhaarNumber": "6789 0123 4567",
    "level": 1,
    "date": "2025-03-03T00:00:00Z",
    "status": "under review",
    "priority": "low",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC018",
    "userName": "Lata Chand",
    "aadhaarNumber": "3344 5566 7788",
    "level": 3,
    "date": "2024-07-28T00:00:00Z",
    "status": "verified",
    "priority": "medium",
    "reviewed": ""
  },
  {
    "ID": "KYC019",
    "userName": "Vivek Nambiar",
    "aadhaarNumber": "7777 6666 5555",
    "level": 2,
    "date": "2025-10-11T00:00:00Z",
    "status": "under review",
    "priority": "high",
    "reviewed": "admin user"
  },
  {
    "ID": "KYC020",
    "userName": "Priya Sethi",
    "aadhaarNumber": "1010 1111 1212",
    "level": 1,
    "date": "2024-06-12T00:00:00Z",
    "status": "rejected",
    "priority": "medium",
    "reviewed": ""
  }
];


export const investmentSchemes = [
  {
    id: "gold1",
    title: "Gold Premium Plan",
    description: "Premium gold investment scheme with guaranteed returns",
    tenure: 24,
    installment: 10000,
    isActive: true
  },
  {
    id: "diamond1",
    title: "Diamond Elite Scheme",
    description: "Exclusive diamond investment with premium benefits",
    tenure: 36,
    installment: 15000,
    isActive: true
  },
  {
    id: "silver1",
    title: "Silver Starter Plan",
    description: "Entry-level silver investment scheme for beginners",
    tenure: 12,
    installment: 2500,
    isActive: true
  },
  {
    id: "platinum1",
    title: "Platinum Pro",
    description: "Professional platinum investment with flexible terms",
    tenure: 48,
    installment: 7500,
    isActive: true
  },
  {
    id: "gold2",
    title: "Gold Classic",
    description: "Classic gold scheme - temporarily suspended",
    tenure: 18,
    installment: 5000,
    isActive: false
  },
  {
    id: "diamond2",
    title: "Diamond Luxury",
    description: "Luxury diamond investment for high-value investors",
    tenure: 36,
    installment: 3000,
    isActive: true
  }
];


export const paymentsData = [
  {
    id: "PAY001",
    userName: "Aarav Patel",
    email: "aarav.patel@example.com",
    schemeName: "Gold Premium Plan",
    installmentsPaid: 12,
    totalInstallments: 24,
    amount: 10000,
    dueDate: "2025-11-10",
    status: "pending",
  },
  {
    id: "PAY002",
    userName: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    schemeName: "Diamond Elite Scheme",
    installmentsPaid: 18,
    totalInstallments: 36,
    amount: 15000,
    dueDate: "2025-11-03",
    status: "paid",
  },
  {
    id: "PAY003",
    userName: "Rohan Sharma",
    email: "rohan.sharma@example.com",
    schemeName: "Silver Starter Plan",
    installmentsPaid: 6,
    totalInstallments: 12,
    amount: 2500,
    dueDate: "2025-10-28",
    status: "overdue",
  },
  {
    id: "PAY004",
    userName: "Meera Iyer",
    email: "meera.iyer@example.com",
    schemeName: "Platinum Pro",
    installmentsPaid: 20,
    totalInstallments: 48,
    amount: 7500,
    dueDate: "2025-11-15",
    status: "paid",
  },
  {
    id: "PAY005",
    userName: "Devansh Gupta",
    email: "devansh.gupta@example.com",
    schemeName: "Gold Classic",
    installmentsPaid: 5,
    totalInstallments: 18,
    amount: 5000,
    dueDate: "2025-10-20",
    status: "overdue",
  },
  {
    id: "PAY006",
    userName: "Ananya Singh",
    email: "ananya.singh@example.com",
    schemeName: "Diamond Luxury",
    installmentsPaid: 10,
    totalInstallments: 36,
    amount: 3000,
    dueDate: "2025-11-02",
    status: "pending",
  },
  {
    id: "PAY007",
    userName: "Karan Mehta",
    email: "karan.mehta@example.com",
    schemeName: "Gold Premium Plan",
    installmentsPaid: 24,
    totalInstallments: 24,
    amount: 10000,
    dueDate: "2025-10-10",
    status: "paid",
  },
  {
    id: "PAY008",
    userName: "Ishita Nair",
    email: "ishita.nair@example.com",
    schemeName: "Silver Starter Plan",
    installmentsPaid: 8,
    totalInstallments: 12,
    amount: 2500,
    dueDate: "2025-11-12",
    status: "partial",
  },
  {
    id: "PAY009",
    userName: "Arjun Das",
    email: "arjun.das@example.com",
    schemeName: "Platinum Pro",
    installmentsPaid: 30,
    totalInstallments: 48,
    amount: 7500,
    dueDate: "2025-11-05",
    status: "pending",
  },
  {
    id: "PAY010",
    userName: "Priya Menon",
    email: "priya.menon@example.com",
    schemeName: "Diamond Elite Scheme",
    installmentsPaid: 35,
    totalInstallments: 36,
    amount: 15000,
    dueDate: "2025-10-30",
    status: "paid",
  },
  {
    id: "PAY011",
    userName: "Nikhil Verma",
    email: "nikhil.verma@example.com",
    schemeName: "Diamond Luxury",
    installmentsPaid: 15,
    totalInstallments: 36,
    amount: 3000,
    dueDate: "2025-10-25",
    status: "overdue",
  },
  {
    id: "PAY012",
    userName: "Aditi Rao",
    email: "aditi.rao@example.com",
    schemeName: "Gold Classic",
    installmentsPaid: 8,
    totalInstallments: 18,
    amount: 5000,
    dueDate: "2025-11-08",
    status: "pending",
  },
  {
    id: "PAY013",
    userName: "Ravi Joshi",
    email: "ravi.joshi@example.com",
    schemeName: "Gold Premium Plan",
    installmentsPaid: 20,
    totalInstallments: 24,
    amount: 10000,
    dueDate: "2025-11-18",
    status: "paid",
  },
  {
    id: "PAY014",
    userName: "Neha Kapoor",
    email: "neha.kapoor@example.com",
    schemeName: "Platinum Pro",
    installmentsPaid: 12,
    totalInstallments: 48,
    amount: 7500,
    dueDate: "2025-11-22",
    status: "pending",
  },
  {
    id: "PAY015",
    userName: "Vikram Sinha",
    email: "vikram.sinha@example.com",
    schemeName: "Silver Starter Plan",
    installmentsPaid: 11,
    totalInstallments: 12,
    amount: 2500,
    dueDate: "2025-10-27",
    status: "partial",
  },
  {
    id: "PAY016",
    userName: "Diya Khanna",
    email: "diya.khanna@example.com",
    schemeName: "Diamond Elite Scheme",
    installmentsPaid: 10,
    totalInstallments: 36,
    amount: 15000,
    dueDate: "2025-11-06",
    status: "pending",
  },
  {
    id: "PAY017",
    userName: "Manav Tiwari",
    email: "manav.tiwari@example.com",
    schemeName: "Gold Classic",
    installmentsPaid: 16,
    totalInstallments: 18,
    amount: 5000,
    dueDate: "2025-10-15",
    status: "paid",
  },
  {
    id: "PAY018",
    userName: "Ritika Jain",
    email: "ritika.jain@example.com",
    schemeName: "Diamond Luxury",
    installmentsPaid: 20,
    totalInstallments: 36,
    amount: 3000,
    dueDate: "2025-11-14",
    status: "paid",
  },
  {
    id: "PAY019",
    userName: "Arnav Roy",
    email: "arnav.roy@example.com",
    schemeName: "Gold Premium Plan",
    installmentsPaid: 15,
    totalInstallments: 24,
    amount: 10000,
    dueDate: "2025-11-01",
    status: "partial",
  },
  {
    id: "PAY020",
    userName: "Sanya Bhatia",
    email: "sanya.bhatia@example.com",
    schemeName: "Platinum Pro",
    installmentsPaid: 40,
    totalInstallments: 48,
    amount: 7500,
    dueDate: "2025-11-09",
    status: "paid",
  },
  {
    id: "PAY021",
    userName: "Tushar Malik",
    email: "tushar.malik@example.com",
    schemeName: "Diamond Elite Scheme",
    installmentsPaid: 8,
    totalInstallments: 36,
    amount: 15000,
    dueDate: "2025-11-04",
    status: "pending",
  },
  {
    id: "PAY022",
    userName: "Pooja Desai",
    email: "pooja.desai@example.com",
    schemeName: "Silver Starter Plan",
    installmentsPaid: 10,
    totalInstallments: 12,
    amount: 2500,
    dueDate: "2025-11-11",
    status: "paid",
  },
  {
    id: "PAY023",
    userName: "Rahul Nanda",
    email: "rahul.nanda@example.com",
    schemeName: "Gold Classic",
    installmentsPaid: 2,
    totalInstallments: 18,
    amount: 5000,
    dueDate: "2025-10-05",
    status: "overdue",
  },
  {
    id: "PAY024",
    userName: "Kavya Pillai",
    email: "kavya.pillai@example.com",
    schemeName: "Diamond Luxury",
    installmentsPaid: 28,
    totalInstallments: 36,
    amount: 3000,
    dueDate: "2025-11-13",
    status: "pending",
  },
  {
    id: "PAY025",
    userName: "Harshad Naik",
    email: "harshad.naik@example.com",
    schemeName: "Platinum Pro",
    installmentsPaid: 47,
    totalInstallments: 48,
    amount: 7500,
    dueDate: "2025-10-01",
    status: "paid",
  },
];


export const reportLogs = [
  {
    id: "RPT-2025-001",
    title: "Monthly Investment Summary - October",
    dateGenerated: "2025-11-01T09:15:00Z",
    type: "investment",
    status: "completed",
    fileInfo: { type: "pdf", size: "2.3 MB" },
    downloads: 24,
    generatedBy: "Aarav Patel",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-002",
    title: "KYC Verification Overview",
    dateGenerated: "2025-11-02T12:30:00Z",
    type: "kyc",
    status: "completed",
    fileInfo: { type: "excel", size: "1.8 MB" },
    downloads: 15,
    generatedBy: "Sneha Reddy",
    designation: "KYC Manager",
  },
  {
    id: "RPT-2025-003",
    title: "Pending Payments Summary - November",
    dateGenerated: "2025-11-03T08:10:00Z",
    type: "payment",
    status: "generating",
    fileInfo: { type: "pdf", size: "—" },
    downloads: 0,
    generatedBy: "Rohan Sharma",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-004",
    title: "User Growth Analytics Q4",
    dateGenerated: "2025-11-04T14:45:00Z",
    type: "user",
    status: "completed",
    fileInfo: { type: "excel", size: "3.2 MB" },
    downloads: 32,
    generatedBy: "Meera Iyer",
    designation: "Data Analyst",
  },
  {
    id: "RPT-2025-005",
    title: "Scheme Performance Report - Gold Plans",
    dateGenerated: "2025-11-05T10:20:00Z",
    type: "scheme",
    status: "failed",
    fileInfo: { type: "pdf", size: "1.1 MB" },
    downloads: 5,
    generatedBy: "Devansh Gupta",
    designation: "Schema Manager",
  },
  {
    id: "RPT-2025-006",
    title: "Investment Growth Projection - FY2025",
    dateGenerated: "2025-11-05T11:40:00Z",
    type: "investment",
    status: "completed",
    fileInfo: { type: "excel", size: "2.9 MB" },
    downloads: 41,
    generatedBy: "Ananya Singh",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-007",
    title: "User Activity Log - November Week 1",
    dateGenerated: "2025-11-05T13:00:00Z",
    type: "user",
    status: "completed",
    fileInfo: { type: "pdf", size: "1.7 MB" },
    downloads: 27,
    generatedBy: "Karan Mehta",
    designation: "Admin User",
  },
  {
    id: "RPT-2025-008",
    title: "KYC Update Failure Logs",
    dateGenerated: "2025-11-05T15:30:00Z",
    type: "kyc",
    status: "failed",
    fileInfo: { type: "excel", size: "1.4 MB" },
    downloads: 3,
    generatedBy: "Ishita Nair",
    designation: "KYC Manager",
  },
  {
    id: "RPT-2025-009",
    title: "Payment Distribution Report - October",
    dateGenerated: "2025-11-04T17:45:00Z",
    type: "payment",
    status: "completed",
    fileInfo: { type: "pdf", size: "2.6 MB" },
    downloads: 18,
    generatedBy: "Arjun Das",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-010",
    title: "Scheme Enrollment Overview",
    dateGenerated: "2025-11-03T10:50:00Z",
    type: "scheme",
    status: "generating",
    fileInfo: { type: "excel", size: "—" },
    downloads: 0,
    generatedBy: "Priya Menon",
    designation: "Schema Manager",
  },
  {
    id: "RPT-2025-011",
    title: "Investment Return Comparison - Q3",
    dateGenerated: "2025-11-02T09:00:00Z",
    type: "investment",
    status: "completed",
    fileInfo: { type: "pdf", size: "2.1 MB" },
    downloads: 22,
    generatedBy: "Nikhil Verma",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-012",
    title: "User Deactivation Audit",
    dateGenerated: "2025-11-01T18:30:00Z",
    type: "user",
    status: "failed",
    fileInfo: { type: "excel", size: "1.5 MB" },
    downloads: 6,
    generatedBy: "Aditi Rao",
    designation: "Admin User",
  },
  {
    id: "RPT-2025-013",
    title: "KYC Pending Verification Report",
    dateGenerated: "2025-11-04T09:25:00Z",
    type: "kyc",
    status: "completed",
    fileInfo: { type: "pdf", size: "1.9 MB" },
    downloads: 12,
    generatedBy: "Ravi Joshi",
    designation: "KYC Manager",
  },
  {
    id: "RPT-2025-014",
    title: "Top Performing Schemes - Q4",
    dateGenerated: "2025-11-05T08:45:00Z",
    type: "scheme",
    status: "completed",
    fileInfo: { type: "excel", size: "3.1 MB" },
    downloads: 29,
    generatedBy: "Neha Kapoor",
    designation: "Schema Manager",
  },
  {
    id: "RPT-2025-015",
    title: "Failed Payment Retry Summary",
    dateGenerated: "2025-11-05T16:10:00Z",
    type: "payment",
    status: "failed",
    fileInfo: { type: "pdf", size: "1.2 MB" },
    downloads: 4,
    generatedBy: "Vikram Sinha",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-016",
    title: "New Users - October Summary",
    dateGenerated: "2025-11-01T08:00:00Z",
    type: "user",
    status: "completed",
    fileInfo: { type: "pdf", size: "2.5 MB" },
    downloads: 25,
    generatedBy: "Diya Khanna",
    designation: "Admin User",
  },
  {
    id: "RPT-2025-017",
    title: "Investment Defaulters Report",
    dateGenerated: "2025-11-05T07:35:00Z",
    type: "investment",
    status: "generating",
    fileInfo: { type: "excel", size: "—" },
    downloads: 0,
    generatedBy: "Manav Tiwari",
    designation: "Finance Head",
  },
  {
    id: "RPT-2025-018",
    title: "KYC Compliance Audit - FY2024",
    dateGenerated: "2025-11-05T09:50:00Z",
    type: "kyc",
    status: "completed",
    fileInfo: { type: "pdf", size: "2.0 MB" },
    downloads: 19,
    generatedBy: "Ritika Jain",
    designation: "KYC Manager",
  },
  {
    id: "RPT-2025-019",
    title: "Scheme Renewal Summary - November",
    dateGenerated: "2025-11-05T10:05:00Z",
    type: "scheme",
    status: "completed",
    fileInfo: { type: "excel", size: "2.8 MB" },
    downloads: 33,
    generatedBy: "Arnav Roy",
    designation: "Schema Manager",
  },
  {
    id: "RPT-2025-020",
    title: "Daily Payment Summary - November 5",
    dateGenerated: "2025-11-05T11:15:00Z",
    type: "payment",
    status: "completed",
    fileInfo: { type: "pdf", size: "2.2 MB" },
    downloads: 11,
    generatedBy: "Sanya Bhatia",
    designation: "Finance Head",
  },
];


export const notifications = [
  {
    id: "NTF-2025-001",
    type: "welcome",
    title: "Welcome to AGD Gold and Diamonds",
    message: "Welcome to AGD Gold and Diamonds! Begin your journey toward smart investments today.",
    status: "sent",
    priority: "medium",
    sentAt: "2025-01-02T08:45:00Z",
    user: { username: "Aarav Patel", email: "aarav.patel@example.com" },
    channels: ["email", "push"],
  },
  {
    id: "NTF-2025-002",
    type: "payment",
    title: "Payment Received - Silver Starter Plan",
    message: "Your payment of ₹10,000 for Silver Starter Plan has been successfully received.",
    status: "delivered",
    priority: "high",
    sentAt: "2025-02-05T14:25:00Z",
    user: { username: "Neha Sharma", email: "neha.sharma@example.com" },
    channels: ["email", "sms"],
  },
  {
    id: "NTF-2025-003",
    type: "kyc",
    title: "KYC Verification Completed",
    message: "Your KYC verification has been successfully completed. You can now invest freely.",
    status: "sent",
    priority: "medium",
    sentAt: "2025-02-10T09:50:00Z",
    user: { username: "Rohan Verma", email: "rohan.verma@example.com" },
    channels: ["email"],
  },
  {
    id: "NTF-2025-004",
    type: "investment",
    title: "Investment Portfolio Updated",
    message: "Your investment portfolio has been updated with new gold plan units.",
    status: "delivered",
    priority: "high",
    sentAt: "2025-03-01T11:10:00Z",
    user: { username: "Simran Kaur", email: "simran.kaur@example.com" },
    channels: ["push", "email"],
  },
  {
    id: "NTF-2025-005",
    type: "scheme",
    title: "New Platinum Growth Scheme Launched",
    message: "Discover our new Platinum Growth Scheme with flexible tenure options.",
    status: "sent",
    priority: "low",
    sentAt: "2025-03-12T16:30:00Z",
    user: { username: "Arjun Mehta", email: "arjun.mehta@example.com" },
    channels: ["push"],
  },
  {
    id: "NTF-2025-006",
    type: "user",
    title: "Profile Updated Successfully",
    message: "Your profile information has been successfully updated.",
    status: "delivered",
    priority: "low",
    sentAt: "2025-03-20T07:40:00Z",
    user: { username: "Priya Iyer", email: "priya.iyer@example.com" },
    channels: ["email", "push"],
  },
  {
    id: "NTF-2025-007",
    type: "payment",
    title: "Payment Failed - Gold Elite Plan",
    message: "We were unable to process your payment for the Gold Elite Plan. Please try again.",
    status: "failed",
    priority: "high",
    sentAt: "2025-03-28T13:55:00Z",
    user: { username: "Vikram Nair", email: "vikram.nair@example.com" },
    channels: ["sms", "email"],
  },
  {
    id: "NTF-2025-008",
    type: "kyc",
    title: "KYC Pending Verification",
    message: "Your KYC documents are under review. You’ll be notified once verification is complete.",
    status: "sent",
    priority: "medium",
    sentAt: "2025-04-04T10:05:00Z",
    user: { username: "Meera Joshi", email: "meera.joshi@example.com" },
    channels: ["email", "push"],
  },
  {
    id: "NTF-2025-009",
    type: "investment",
    title: "Monthly Investment Report - March",
    message: "Your March investment report is now available for download.",
    status: "delivered",
    priority: "medium",
    sentAt: "2025-04-06T18:15:00Z",
    user: { username: "Rajat Singh", email: "rajat.singh@example.com" },
    channels: ["email"],
  },
  {
    id: "NTF-2025-010",
    type: "scheme",
    title: "Scheme Renewal Reminder",
    message: "Your Silver Starter Plan will expire soon. Renew now to continue enjoying benefits.",
    status: "sent",
    priority: "high",
    sentAt: "2025-04-10T09:20:00Z",
    user: { username: "Sneha Kapoor", email: "sneha.kapoor@example.com" },
    channels: ["sms", "push"],
  },
  {
    id: "NTF-2025-011",
    type: "user",
    title: "Password Changed Successfully",
    message: "Your password was changed successfully. If this wasn’t you, contact support immediately.",
    status: "delivered",
    priority: "high",
    sentAt: "2025-04-15T06:45:00Z",
    user: { username: "Rahul Das", email: "rahul.das@example.com" },
    channels: ["email"],
  },
  {
    id: "NTF-2025-012",
    type: "payment",
    title: "Auto-Payment Scheduled",
    message: "An auto-payment of ₹5,000 has been scheduled for your Platinum Plan.",
    status: "sent",
    priority: "medium",
    sentAt: "2025-04-18T17:25:00Z",
    user: { username: "Divya Menon", email: "divya.menon@example.com" },
    channels: ["push"],
  },
  {
    id: "NTF-2025-013",
    type: "investment",
    title: "Quarterly Dividend Credited",
    message: "A dividend payout has been credited to your account.",
    status: "delivered",
    priority: "medium",
    sentAt: "2025-04-25T14:55:00Z",
    user: { username: "Ankit Bhatia", email: "ankit.bhatia@example.com" },
    channels: ["email", "push"],
  },
  {
    id: "NTF-2025-014",
    type: "scheme",
    title: "Exclusive Offer on Diamond Plan",
    message: "Get 10% extra benefit when investing in the Diamond Plan before May 31.",
    status: "sent",
    priority: "high",
    sentAt: "2025-05-01T08:10:00Z",
    user: { username: "Kavya Rao", email: "kavya.rao@example.com" },
    channels: ["push", "sms"],
  },
  {
    id: "NTF-2025-015",
    type: "welcome",
    title: "Welcome to AGD Gold and Diamonds",
    message: "Welcome aboard, Kiran! Start investing smartly with AGD Gold and Diamonds.",
    status: "delivered",
    priority: "low",
    sentAt: "2025-05-03T09:00:00Z",
    user: { username: "Kiran Thomas", email: "kiran.thomas@example.com" },
    channels: ["email"],
  },
  {
    id: "NTF-2025-016",
    type: "payment",
    title: "Payment Reminder - Silver Plan",
    message: "Your upcoming payment of ₹3,000 is due in 2 days. Please make sure to complete it on time.",
    status: "sent",
    priority: "medium",
    sentAt: "2025-05-10T19:45:00Z",
    user: { username: "Nisha Jain", email: "nisha.jain@example.com" },
    channels: ["email", "push"],
  },
  {
    id: "NTF-2025-017",
    type: "user",
    title: "Two-Factor Authentication Enabled",
    message: "You’ve successfully enabled two-factor authentication for your AGD account.",
    status: "delivered",
    priority: "low",
    sentAt: "2025-05-14T11:35:00Z",
    user: { username: "Aditya Roy", email: "aditya.roy@example.com" },
    channels: ["push"],
  },
  {
    id: "NTF-2025-018",
    type: "investment",
    title: "Gold Value Increased by 5%",
    message: "Your gold investment portfolio has appreciated by 5% in the past month.",
    status: "sent",
    priority: "medium",
    sentAt: "2025-05-20T07:15:00Z",
    user: { username: "Tanvi Shah", email: "tanvi.shah@example.com" },
    channels: ["email", "push"],
  },
  {
    id: "NTF-2025-019",
    type: "scheme",
    title: "Scheme Maturity Notice",
    message: "Your Gold Premium Plan is reaching maturity next week. Redeem or reinvest now.",
    status: "delivered",
    priority: "high",
    sentAt: "2025-05-27T13:20:00Z",
    user: { username: "Siddharth Rao", email: "siddharth.rao@example.com" },
    channels: ["email"],
  },
  {
    id: "NTF-2025-020",
    type: "kyc",
    title: "KYC Document Expiring Soon",
    message: "Your KYC document is set to expire soon. Please upload updated proof to continue services.",
    status: "sent",
    priority: "high",
    sentAt: "2025-06-01T15:10:00Z",
    user: { username: "Pooja Nair", email: "pooja.nair@example.com" },
    channels: ["email", "sms", "push"],
  },
];

